config/routes.rb
Rails.application.routes.draw do
 

  resources :meetings
  devise_for :users
  resources :users

 
  resources :accounts do
  	resources :service_comments do
  	end
  end

 

  resources :accounts do
    resources :stores do
    end
  end

  resources :stores do
    resources :service_records do
      end
  end

  resources :subcontractors do
    resources :employees do
    end
  end
  
  resources :employees 
  resources :stores
  resources :service_records
  resources :calendar 

  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord

	def self.search(search)
    where("name ILIKE ? OR subcontractor ILIKE ? OR division ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
    end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.order("created_at ASC").paginate(page: params[:page], per_page: 10)

    if params[:search]
    @meetings = Meeting.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 10)
    else
    @meetings = Meeting.order("created_at ASC").paginate(page: params[:page], per_page: 10)
    end

  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show

  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :subcontractor, :division, :start_time, :end_time)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :meeting_name %>
  </div>

   <div class="field">
    <%= form.label :subcontractor %>
    <%= form.text_field :subcontractor, id: :meeting_subcontractor %>
  </div>

  <div class="field">
    <%= form.label :division %>
    <%= form.text_field :division, id: :meeting_division %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :meeting_start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :meeting_end_time %>
  </div>
<% if policy(Account.new).create? %>
  <div class="actions">

    <%= form.submit "Create Event" %>
  </div>
  <% end %>
  <br>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scheduled Events</h1>

<table style="border-spacing: 20px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Subcontractor</th>
      <th>Division &nbsp; &nbsp;</th>
      <th>Start time</th>
      <th>End time</th>
      <td colspan="3"></td>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %> &nbsp; &nbsp;</td>
        <td><%= meeting.subcontractor %> &nbsp; &nbsp;</td>
        <td><%= meeting.division %> &nbsp; &nbsp; </td>
        <td><%= meeting.start_time %> &nbsp; &nbsp;</td>
        <td><%= meeting.end_time %> &nbsp; &nbsp;</td>
        <% if policy(Account.new).create? %>
        <td><%= link_to 'Show', meeting %> &nbsp;</td>
        <% end %>
        <% if policy(Account.new).create? %>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %> &nbsp;</td>
        <% end %>
        <% if policy(Account.new).create? %>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %> &nbsp;</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @meetings %>
<br>

<%= form_tag(meetings_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search Events by Subcontractor of Division" %>
    <br>
    <%= submit_tag "Search", :name => nil, class: 'btn btn-success' %>
<% end %>

<% if @meetings.blank? %>
  <h4>There are no Events containing the term <%= params[:search] %>. Please check spelling and try again. </h4>
<% end %>

<br>

<%= link_to 'New Event', new_meeting_path %>
<br>&nbsp;<br>
<%= month_calendar events: @meetings do |date, meetings| %>
  <%= date %>

  <% meetings.each do |meeting| %>
    <div>
      <b><em>Event: <%= meeting.name %> &nbsp; <br> Sub: <%= meeting.subcontractor %> &nbsp; Division: <%= meeting.division %> &nbsp; </em></b>
    </div>
  <% end %>
  
<% end %>

app/views/meetings/new.html.erb
<h1>New Event</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Subcontractor:</strong>
  <%= @meeting.subcontractor %>
</p>
<p>
	<strong>Division:</strong>
	<%= @meeting.division %> 
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>