config/routes.rb
Rails.application.routes.draw do
 

  resources :meetings
  devise_for :users
  resources :users

 
  resources :accounts do
  	resources :service_comments do
  	end
  end

 

  resources :accounts do
    resources :stores do
    end
  end

  resources :stores do
    resources :service_records do
      end
  end

  resources :subcontractors do
    resources :employees do
    end
  end
  
  resources :employees 
  resources :stores
  resources :service_records
  resources :calendar 

  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subcontractor.rb
class Subcontractor < ApplicationRecord
	has_many :employees, dependent: :destroy  

	def self.search(search)
    where("name ILIKE ? OR subcontractor_number ILIKE ? OR federal_number ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
    end


end

app/controllers/subcontractors_controller.rb
class SubcontractorsController < ApplicationController
  def index
    @subcontractors = Subcontractor.order(:name).paginate(page: params[:page], per_page: 10)
    
  if params[:search]
    @subcontractors = Subcontractor.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 10)
  else
    @subcontractors = Subcontractor.order(:name).paginate(page: params[:page], per_page: 10)
  end

  end

  def show
  	@subcontractor = Subcontractor.find(params[:id])
    @all_employees = @subcontractor.employees.all.order('created_at DESC')
    @employees = @subcontractor.employees.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    @employee = @subcontractor.employees.build
  end

  def new
    @subcontractor = Subcontractor.new 
    

  end

  def create
    @subcontractor = Subcontractor.new(params.require(:subcontractor).permit(:name, :subcontractor_number, :owner, :address_1, :address_2, :city_state_zip,
     :phone_number, :email_address, :division, :route, :active, :business_license, :federal_number, :sca_rec, :sca_exp, :lwa_rec, :Nsqc_rec, :psqc, :bookkeeper,
     :lettstat, :chk_acct, :liability_carrier, :liability_expiration, :wcmp_car, :wcmp_exp))
   
    if @subcontractor.save
      flash[:notice] = "Subcontractor was successfully saved."
      redirect_to @subcontractor
    else
      flash[:error] = "There was an error saving your new subcontractor. Please try again."
      render :new
    end
  end

  def edit
    @subcontractor = Subcontractor.find(params[:id])
  end

  def update
    @subcontractor = Subcontractor.find(params[:id])
    if @subcontractor.update_attributes(params.require(:subcontractor).permit(:name, :subcontractor_number, :owner, :address_1, :address_2, :city_state_zip,
     :phone_number, :email_address, :division, :route, :active, :business_license, :federal_number, :sca_rec, :sca_exp, :lwa_rec, :Nsqc_rec, :psqc, :bookkeeper,
     :lettstat, :chk_acct, :liability_carrier, :liability_expiration, :wcmp_car, :wcmp_exp))
    flash[:notice] = "Subcontractor was updated."
    redirect_to @subcontractor
  else
    flash[:error] = "There was an error saving this subcontractor. Please try again."
    render :edit
  end
end

def destroy
@subcontractor = Subcontractor.find(params[:id])

  if @subcontractor.destroy 
    flash[:notice] = "\"#{@subcontractor.name}\" was deleted successfully."
    redirect_to subcontractors_path 
  else
    flash[:error] = "There was an error deleting this subcontractor. Please try again."
    render :show
  end
end

end

app/views/subcontractors/edit.html.erb
<h1>Edit Subcontractor</h1>

<div class="row">
	<div class="col-md-4">
		<p> Please fill out form completely and accurately. </p>
		<p> If any issues saving accounts are experienced, please contact your web developer. </p>
	</div>

	<div class="col-md-8">
 <%= form_for @subcontractor do |f| %>
 	<div class="form-group">
   <%= f.label "Subcontractor Name" %>
   <%= f.text_field :name, class: 'form-control', placeholder: "Enter Subcontractor Name" %>
    </div>
    <div class="form-group">
    <%= f.label "Subcontractor Number" %>
    <%= f.text_field :subcontractor_number %>
	</div>
    <div class="form-group">
    <%= f.label "Owner" %>
    <%= f.text_field :owner %>
    </div>
    <div class="form-group">
    <%= f.label "Active?" %>
    <%= f.check_box :active %>
	</div>
    <div class="form-group">
    <%= f.label "Address 1" %>
    <%= f.text_field :address_1 %>
	</div> 
	<div class="form-group">
    <%= f.label "Address 2" %>
    <%= f.text_field :address_2 %>
    </div>
    <div class="form-group">
   <%= f.label "City, State, and Zip Code" %>
   <%= f.text_field :city_state_zip %>
    </div>
    <div class="form-group">
   <%= f.label "Phone Number" %>
   <%= f.text_field :phone_number %>
    </div>
   <div class="form-group">
   <%= f.label "Email Address" %>
   <%= f.text_field :email_address %>
   </div>
   <div class="form-group">
   <%= f.label "Division"%>
   <%= f.text_field :division %>
   </div>
   <div class="form-group">
   <%= f.label "Route" %>
   <%= f.text_field :route %>
	</div>
	<div class="form-group"> 
   <%= f.label "Phone" %>
   <%= f.text_field :business_license %>
	</div>
	<div class="form-group">
   <%= f.label "Email" %>
   <%= f.text_field :federal_number %>
	</div>
	<div class="form-group">
   <%= f.label "SCA " %>
   <%= f.text_field :sca_rec %>
    </div>
    <div class="form-group">
   <%= f.label "SCA Expiration Date" %>
   <%= f.text_field :sca_exp %>
	</div>
	<div class="form-group">
   <%= f.label "LWA" %>
   <%= f.text_field :lwa_rec %>
	</div>
	<div class="form-group">
   <%= f.label "NSQC" %>
   <%= f.text_field :Nsqc_rec %>
	</div>
	<div class="form-group">
   <%= f.label "PSQC" %>
   <%= f.text_field :psqc %>
   </div>
   <div class="form-group">
   <%= f.label "Bookkeeper" %>
   <%= f.text_field :bookkeeper %>
	</div>
	<div class="form-group">
   <%= f.label "Lettstat" %>
   <%= f.text_field :lettstat %>
   </div>
   <div class="form-group">
   <%= f.label "Checking Account" %>
   <%= f.text_field :chk_acct %>
   </div>
   <div class="form-group">
   <%= f.label "Liability Carrier" %>
   <%= f.text_field :liability_carrier %>
   </div>
   <div class="form-group">
   <%= f.label "Liability Expiration" %>
   <%= f.text_field :liability_expiration %>
   </div>
   <div class="form-group">
   <%= f.label "Workman's Comp Carrier" %>
   <%= f.text_field :wcmp_car %>
   </div>
   <div class="form-group">
   <%= f.label "Workman's Comp Expiration" %>
   <%= f.text_field :wcmp_exp %>
	</div>
 	<div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
 </div>
 <% end %>

app/views/subcontractors/index.html.erb
<h1>All Subcontractors</h1>
<br>
<% if policy(Account.new).create? %>
<p><%= link_to '<button type="button" class="btn btn-default">Create New Subcontractor</button>'.html_safe, new_subcontractor_path %></p>
<% end %> 
<br>

<%= form_tag(subcontractors_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search Subcontractors" %>
    <br>
    <%= submit_tag "Search", :name => nil, class: 'btn btn-success' %>
<% end %>

<% if @subcontractors.blank? %>
  <h4>There are no Subcontractors containing the term <%= params[:search] %>.</h4>
<% end %>

<br>

<% @subcontractors.each do |subcontractor| %>
  
  <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <p><%= link_to subcontractor.name, subcontractor_path(subcontractor.id) %></p>
       </h4>
     </div>
   </div>
<% end %>
<%= will_paginate @subcontractors %>

app/views/subcontractors/new.html.erb
<h1>Create Subcontractor</h1>

<div class="row">
	<div class="col-md-4">
		<p> Please fill out form completely and accurately. </p>
		<p> If any issues saving accounts are experienced, please contact your web developer. </p>
	</div>

	<div class="col-md-8">
 <%= form_for @subcontractor do |f| %>
 	<div class="form-group">
   <%= f.label "Subcontractor Name" %>
   <%= f.text_field :name, class: 'form-control', placeholder: "Enter Subcontractor Name" %>
    </div>
    <div class="form-group">
    <%= f.label "Subcontractor Number" %>
    <%= f.text_field :subcontractor_number %>
	</div>
    <div class="form-group">
    <%= f.label "Owner" %>
    <%= f.text_field :owner %>
    </div>
    <div class="form-group">
    <%= f.label "Active?" %>
    <%= f.check_box :active %>
	</div>
    <div class="form-group">
    <%= f.label "Address 1" %>
    <%= f.text_field :address_1 %>
	</div> 
	<div class="form-group">
    <%= f.label "Address 2" %>
    <%= f.text_field :address_2 %>
    </div>
    <div class="form-group">
   <%= f.label "City, State, and Zip Code" %>
   <%= f.text_field :city_state_zip %>
    </div>
    <div class="form-group">
   <%= f.label "Phone Number" %>
   <%= f.text_field :phone_number %>
    </div>
   <div class="form-group">
   <%= f.label "Email Address" %>
   <%= f.text_field :email_address %>
   </div>
   <div class="form-group">
   <%= f.label "Division"%>
   <%= f.text_field :division %>
   </div>
   <div class="form-group">
   <%= f.label "Route" %>
   <%= f.text_field :route %>
	</div>
	<div class="form-group"> 
   <%= f.label "Business License" %>
   <%= f.text_field :business_license %>
	</div>
	<div class="form-group">
   <%= f.label "Email" %>
   <%= f.text_field :federal_number %>
	</div>
	<div class="form-group">
   <%= f.label "SCA " %>
   <%= f.text_field :sca_rec %>
    </div>
    <div class="form-group">
   <%= f.label "SCA Expiration Date" %>
   <%= f.text_field :sca_exp %>
	</div>
	<div class="form-group">
   <%= f.label "LWA" %>
   <%= f.text_field :lwa_rec %>
	</div>
	<div class="form-group">
   <%= f.label "NSQC" %>
   <%= f.text_field :Nsqc_rec %>
	</div>
	<div class="form-group">
   <%= f.label "PSQC" %>
   <%= f.text_field :psqc %>
   </div>
   <div class="form-group">
   <%= f.label "Bookkeeper" %>
   <%= f.text_field :bookkeeper %>
	</div>
	<div class="form-group">
   <%= f.label "Lettstat" %>
   <%= f.text_field :lettstat %>
   </div>
   <div class="form-group">
   <%= f.label "Checking Account" %>
   <%= f.text_field :chk_acct %>
   </div>
   <div class="form-group">
   <%= f.label "Liability Carrier" %>
   <%= f.text_field :liability_carrier %>
   </div>
   <div class="form-group">
   <%= f.label "Liability Expiration" %>
   <%= f.text_field :liability_expiration %>
   </div>
   <div class="form-group">
   <%= f.label "Workman's Comp Carrier" %>
   <%= f.text_field :wcmp_car %>
   </div>
   <div class="form-group">
   <%= f.label "Workman's Comp Expiration" %>
   <%= f.text_field :wcmp_exp %>
	</div>
 	<div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
 </div>
 <% end %>

app/views/subcontractors/show.html.erb
<div class="row">
<div>
<h2> Subcontractor Name: <%= @subcontractor.name %></h2>
<% if policy(Account.new).create? %>
<%= link_to "Edit", edit_subcontractor_path(@subcontractor), class: 'btn btn-success' %>
<% end %>
<% if policy(Account.new).destroy? %>
 <%= link_to "Delete Subcontractor", @subcontractor, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this subcontractor?' } %>
<% end %> 
<p><h5>Subcontractor Number:</h5> <%= @subcontractor.subcontractor_number %></p>
<p><h5>Address 1:</h5> <%= @subcontractor.address_1 %></p>
<p><h5>Address 2:</h5> <%= @subcontractor.address_2 %></p>
<p><h5>City, State, and Zipcode:</h5> <%= @subcontractor.city_state_zip %></p>
<p><h5>Primary Phone Number:</h5> <%= @subcontractor.phone_number %></p>
<p><h5>Email Address:</h5> <%= @subcontractor.email_address %></p>
<p><h5>Owner:</h5> <%= @subcontractor.owner %></p>
<p><h5>Division: </h5> <%= @subcontractor.division %></p>
<p><h5>Route:</h5> <%= @subcontractor.route %></p>
<p><h5>Business License:</h5> <%= @subcontractor.business_license %></p>
<p><h5>Federal Number:</h5> <%= @subcontractor.federal_number %></p> 
<p><h5>SCA:</h5> <%= @subcontractor.sca_rec %></p>
<p><h5>SCA Expiration:</h5> <%= @subcontractor.sca_exp %></p>
<p><h5>LWA:</h5> <%= @subcontractor.lwa_rec %></p>
<p><h5>NSQC:</h5> <%= @subcontractor.Nsqc_rec %></p>
<p><h5>PSQC:</h5> <%= @subcontractor.psqc %></p>
<p><h5>Bookkeeper:</h5> <%= @subcontractor.bookkeeper %></p>
<p><h5>Lettstat:</h5> <%= @subcontractor.lettstat %></p>
<p><h5>Checking Account:</h5><%= @subcontractor.chk_acct %></p>
<p><h5>Liability Carrier:</h5><%= @subcontractor.liability_carrier %></p>
<p><h5>Liability Expiration:</h5> <%= @subcontractor.liability_expiration %></p>
<p><h5>Workman's Comp Carrier:</h5> <%= @subcontractor.wcmp_car %></p>
<p><h5>Workman's Comp Expiration:</h5> <%= @subcontractor.wcmp_exp %></p>
<p><h5>Active?</h5> <%= @subcontractor.active ? "yes" : "no" %></p>
</div>

<div class="row">
   <h2>Employees</h2>

   <% @all_employees.each do |employee| %>
   
  <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <p><%= link_to employee.name, employee_path(employee.id) %></p>
       </h4>
     </div>
   </div>
<% end %>

   
     <%= render @employees %>
     <%= will_paginate @employees %>
     <%= render 'employees/form', employee: @employee, subcontractor: @subcontractor %>
    
  </div> 
 <hr>