config/routes.rb
Rails.application.routes.draw do
 

  resources :meetings
  devise_for :users
  resources :users

 
  resources :accounts do
  	resources :service_comments do
  	end
  end

 

  resources :accounts do
    resources :stores do
    end
  end

  resources :stores do
    resources :service_records do
      end
  end

  resources :subcontractors do
    resources :employees do
    end
  end
  
  resources :employees 
  resources :stores
  resources :service_records
  resources :calendar 

  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :account
  has_many :service_records
 
  validates :account_id, presence: true 
  
=begin the below sql query works for heroku's postgre sql system (production environment) and will give an error
in the current mysql development environment.
=end 

	def self.search(search)
    where("name ILIKE ? OR chain ILIKE ? OR district ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
    end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
  	@stores = Store.order(:name).paginate(page: params[:page], per_page: 10)

    if params[:search]
      @stores = Store.search(params[:search]).order(:name).paginate(page: params[:page], per_page: 10)
    else
      @stores = Store.order(:name).paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    @store = Store.find(params[:id]) 
    @service_records = @store.service_records.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    @service_record = @store.service_records.build 
  end

  def create
 
     @account = Account.find(params[:account_id])
     @store = @account.stores.new(store_params)
 
    if @store.save
     redirect_to [@account], notice: "Store saved successfully."
    else
      redirect_to [@account], notice: "Store failed to save."
    end
  end


  def new
    @store = Store.new 
  end


  
  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    
    if @store.update_attributes(params.require(:store).permit(:name, :chain, :code, :phone, :manager, :store, :region, :district, :active, :phone_number, :square_footage, :frequency, :sp_sub, :sp_corp, :address, :zipcode, :state, :city))
    flash[:notice] = "Store was updated."
    redirect_to @store
  else
    flash[:error] = "There was an error saving this store. Please try again."
    render :edit
  end
end

  def destroy
    @account = Account.find(params[:account_id])
    @store = @account.stores.find(params[:id])
  if @store.destroy 
    flash[:notice] = "Store was deleted successfully."
    redirect_to @account
  else
    flash[:error] = "There was an error deleting this store. Please try again."
    redirect_to @account
  end
end

  private 

  def store_params
    params.require(:store).permit(:name, :chain, :code, :phone, :manager, :store, :region, :district, :active, :phone_number, :square_footage, :frequency, :sp_sub, :sp_corp, :address, :zipcode, :state, :city)
  end




end

app/views/stores/_form.html.erb
<% if current_user %>
    <h2>Create New Store</h2>
	<div class="col-md-8">
		<p> Please fill out form completely and accurately. </p>
		<p> If any issues saving accounts are experienced, please contact your web developer </p>
	</div>

	<div class="col-md-8">
 <%= form_for [account, store] do |f| %>
 	<div class="form-group">
   <%= f.label "Store Name" %>
   <%= f.text_field :name, class: 'form-control', placeholder: "Enter Store Name" %>
    </div>
    <div class="form-group">
    <%= f.label "Code" %>
    <%= f.text_field :code %>
	</div>
    <div class="form-group">
    <%= f.label "Manager" %>
    <%= f.text_field :manager %>
    </div>
     <div class="form-group">
    <%= f.label "Address" %>
    <%= f.text_field :address %>
    </div>
     <div class="form-group">
    <%= f.label "Zip Code" %>
    <%= f.text_field :zipcode %>
    </div>
     <div class="form-group">
    <%= f.label "State" %>
    <%= f.text_field :state %>
    </div>
    <div class="form-group">
    <%= f.label "City" %>
    <%= f.text_field :city %>
    </div>
    <div class="form-group">
    <%= f.label "Active?" %>
    <%= f.check_box :active %>
	</div>
    <div class="form-group">
    <%= f.label "Phone Number" %>
    <%= f.text_field :phone_number %>
	</div> 
	<div class="form-group">
    <%= f.label "Region" %>
    <%= f.text_field :region %>
    </div> 
    <div class="form-group">
    <%= f.label "District" %>
    <%= f.text_field :district %>
    </div> 
    <div class="form-group">
    <%= f.label "Chain" %>
    <%= f.text_field :chain %>
    </div> 
     <div class="form-group">
    <%= f.label "Service Type" %>
    <p> Please select from the following service types and enter below: 
        <ul>
            <li>1 Basic</li>
            <li>2 Front Strip</li>
            <li>3 Back Strip</li>
            <li> 4 Extraction</li>
            <li>5 Scrub</li>
            <li>6 Back Scrub</li>
            <li> Windows</li>
            <li>8 Grand Opening</li>
            <li>9 ½ Strip</li>
            <li>10 Other</li>
            <li>11 Corrective Basic</li>
            <li>12 Corrective Front Strip</li>
            <li>13 Corrective Back Strip</li>
            <li>14 Corrective Extraction</li>
            <li>15 Corrective Scrub</li>
            <li>16 Corrective Buff</li>
            <li>17 Corrective Windows</li>
            <li>18 P-Wash</li>
            <li>19 Construction Clean Up</li>
            <li>20 Store Miss</li>
            <li>21 Store Canceled</li>
            <li>22 We Canceled</li>
            <li>23 We Missed </li>
            <li>24 AWOL </li>
            <li>25 Vehicle Problems</li>
            <li>26 Refurbish </li>
            <li>27     Partial Refurbish</li>
            <li>28     Support Area Strip</li>
        </ul>
    </p>
    <%= f.text_field :service_type, class: 'form-control', placeholder: "Enter Service Type" %>
    </div>
    <div class="form-group">
    <%= f.label "Frequency" %>
    <p> Please enter the frequency for each service type input above. For example, '1 - weekly, 2 - annually, 4 - daily' if there are multiple service types. </p>
    <%= f.text_field :frequency, class: 'form-control', placeholder: "Enter Frequency" %>
    </div>
    <div class="form-group">
    <%= f.label "Service Price - Contractor" %>
    <p> Please enter the Contractor service price for each service type.  For example ' 1 - $3400, 2 - $12,000'
    <%= f.text_field :sp_sub, class: 'form-control', placeholder: "Enter Service Price for Contractor" %>
    </div>
    <div class="form-group">
    <%= f.label "Service Price - Corporate" %>
    <p> Please enter the Corporate service price for each service type.  For example ' 1 - $3400, 2 - $12,000'
    <%= f.text_field :sp_corp, class: 'form-control', placeholder: "Enter Service Price for Corporate" %>
    </div>
    <div class="form-group">
    <%= f.label "Square Footage and Floor Type" %>
    <p> Please enter the square footage of the store and the floor type worked upon. For example ' 1400 sq ft - linoleum'
    <%= f.text_field :square_footage, class: 'form-control', placeholder: "Enter Square Footage and Floor Type" %>
    </div>
 	<div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
 	<% end %>
	</div>
</div>
<% end %> 

app/views/stores/_store.html.erb
<% if store.account %>
   <div>
    <% if policy(Account.new).destroy? %>
   	<%= link_to "Delete Store", [@account, store], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this store?' } %>
    <% end %>
   	 <h5> Store Name: <%= store.name %></h5>
      <p><h5>Store Code:</h5> <%= store.code %></p>
      <p><h5>Manager:</h5> <%= store.manager %></p>
      <p><h5>Address:</h5> <%= store.address %></p>
      <p><h5>Zip Code:</h5> <%= store.zipcode %></p>
      <p><h5>City:</h5> <%= store.city %></p>
      <p><h5>State:</h5> <%= store.state %></p>
      <p><h5>Phone:</h5> <%= store.phone_number %></p>
      <p><h5>Region</h5> <%= store.region %></p>
      <p><h5>District:</h5> <%= store.district %></p>
      <p><h5>Chain:</h5> <%= store.chain %></p>
      <p><h5>Frequency:</h5> <%= store.frequency %></p>
      <p><h5>Service Price - Contractor:</h5> <%= store.sp_sub %></p>
      <p><h5>Service Price - Corporate:</h5> <%= store.sp_corp %></p>
      <p><h5>Square Footage & Floor Type:</h5> <%= store.square_footage %></p>
     <small>
       <em><%= store.account.name || store.account.email %> </em>
     </small>
   <% end %>
   <hr/>
 </div>

app/views/stores/edit.html.erb
<h1>Edit Store </h1>
<div class="col-md-8">
        <p> Please fill out form completely and accurately. </p>
        <p> If any issues saving accounts are experienced, please contact your web developer </p>
    </div>

    <div class="col-md-8">
 <%= form_for [@store] do |f| %>
    <div class="form-group">
   <%= f.label "Store Name" %>
   <%= f.text_field :name, class: 'form-control', placeholder: "Enter Store Name" %>
    </div>
    <div class="form-group">
    <%= f.label "Code" %>
    <%= f.text_field :code %>
    </div>
    <div class="form-group">
    <%= f.label "Manager" %>
    <%= f.text_field :manager %>
    </div>
     <div class="form-group">
    <%= f.label "Address" %>
    <%= f.text_field :address %>
    </div>
     <div class="form-group">
    <%= f.label "Zip Code" %>
    <%= f.text_field :zipcode %>
    </div>
     <div class="form-group">
    <%= f.label "State" %>
    <%= f.text_field :state %>
    </div>
    <div class="form-group">
    <%= f.label "City" %>
    <%= f.text_field :city %>
    </div>
    <div class="form-group">
    <%= f.label "Active?" %>
    <%= f.check_box :active %>
    </div>
    <div class="form-group">
    <%= f.label "Phone Number" %>
    <%= f.text_field :phone_number %>
    </div> 
    <div class="form-group">
    <%= f.label "Region" %>
    <%= f.text_field :region %>
    </div> 
    <div class="form-group">
    <%= f.label "District" %>
    <%= f.text_field :district %>
    </div> 
    <div class="form-group">
    <%= f.label "Chain" %>
    <%= f.text_field :chain %>
    </div> 
     <div class="form-group">
    <%= f.label "Service Type" %>
    <p> Please select from the following service types and enter below: 
        <ul>
            <li>1 Basic</li>
            <li>2 Front Strip</li>
            <li>3 Back Strip</li>
            <li> 4 Extraction</li>
            <li>5 Scrub</li>
            <li>6 Back Scrub</li>
            <li> Windows</li>
            <li>8 Grand Opening</li>
            <li>9 ½ Strip</li>
            <li>10 Other</li>
            <li>11 Corrective Basic</li>
            <li>12 Corrective Front Strip</li>
            <li>13 Corrective Back Strip</li>
            <li>14 Corrective Extraction</li>
            <li>15 Corrective Scrub</li>
            <li>16 Corrective Buff</li>
            <li>17 Corrective Windows</li>
            <li>18 P-Wash</li>
            <li>19 Construction Clean Up</li>
            <li>20 Store Miss</li>
            <li>21 Store Canceled</li>
            <li>22 We Canceled</li>
            <li>23 We Missed </li>
            <li>24 AWOL </li>
            <li>25 Vehicle Problems</li>
            <li>26 Refurbish </li>
            <li>27     Partial Refurbish</li>
            <li>28     Support Area Strip</li>
        </ul>
    </p>
    <%= f.text_field :service_type, class: 'form-control', placeholder: "Enter Service Type" %>
    </div>
    <div class="form-group">
    <%= f.label "Frequency" %>
    <p> Please enter the frequency for each service type input above. For example, '1 - weekly, 2 - annually, 4 - daily' if there are multiple service types. </p>
    <%= f.text_field :frequency, class: 'form-control', placeholder: "Enter Frequency" %>
    </div>
    <div class="form-group">
    <%= f.label "Service Price - Contractor" %>
    <p> Please enter the Contractor service price for each service type.  For example ' 1 - $3400, 2 - $12,000'
    <%= f.text_field :sp_sub, class: 'form-control', placeholder: "Enter Service Price for Contractor" %>
    </div>
    <div class="form-group">
    <%= f.label "Service Price - Corporate" %>
    <p> Please enter the Corporate service price for each service type.  For example ' 1 - $3400, 2 - $12,000'
    <%= f.text_field :sp_corp, class: 'form-control', placeholder: "Enter Service Price for Corporate" %>
    </div>
    <div class="form-group">
    <%= f.label "Square Footage and Floor Type" %>
    <p> Please enter the square footage of the store and the floor type worked upon. For example ' 1400 sq ft - linoleum'
    <%= f.text_field :square_footage, class: 'form-control', placeholder: "Enter Square Footage and Floor Type" %>
    </div>
    <div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
    </div>
</div>

app/views/stores/index.html.erb
<h1>All Stores</h1>

<br>

<%= form_tag(stores_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search Stores" %>
    <br>
    <%= submit_tag "Search", :name => nil, class: 'btn btn-success' %>
<% end %>

<% if @stores.blank? %>
  <h4>There are no stores containing the term <%= params[:search] %>.</h4>
<% end %>

<br>

 <% @stores.each do |store| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to store.name, store %>
       </h4>
     </div>
   </div>
   <% end %>
   <%= will_paginate @stores %>

app/views/stores/new.html.erb
<h1>Create New Store </h1>
<div class="row">
	<div class="col-md-4">
		<p> Please fill out form completely and accurately. </p>
		<p> If any issues saving accounts are experienced, please contact your web developer </p>
	</div>

	<div class="col-md-8">
 <%= form_for @account do |f| %>
 	<div class="form-group">
   <%= f.label "Store Name" %>
   <%= f.text_field :name, class: 'form-control', placeholder: "Enter Store Name" %>
    </div>
    <div class="form-group">
    <%= f.label "Code" %>
    <%= f.text_field :code %>
	</div>
    <div class="form-group">
    <%= f.label "Manager" %>
    <%= f.text_field :manager %>
    </div>
    <div class="form-group">
    <%= f.label "Address" %>
    <%= f.text_field :address %>
    </div>
     <div class="form-group">
    <%= f.label "Zip Code" %>
    <%= f.text_field :zipcode %>
    </div>
     <div class="form-group">
    <%= f.label "State" %>
    <%= f.text_field :state %>
    </div>
    <div class="form-group">
    <%= f.label "City" %>
    <%= f.text_field :city %>
    </div>
    <div class="form-group">
    <%= f.label "Active?" %>
    <%= f.check_box :active %>
	</div>
    <div class="form-group">
    <%= f.label "Phone Number" %>
    <%= f.text_field :phone_number %>
	</div> 
    <div class="form-group">
    <%= f.label "Region" %>
    <%= f.text_field :region %>
    </div> 
    <div class="form-group">
    <%= f.label "District" %>
    <%= f.text_field :district %>
    </div> 
    <div class="form-group">
    <%= f.label "Chain" %>
    <%= f.text_field :chain %>
    </div> 

     <div class="form-group">
    <%= f.label "Service Type" %>
    <p> Please select from the following service types and enter below: 
        <ul>
            <li>1 Basic</li>
            <li>2 Front Strip</li>
            <li>3 Back Strip</li>
            <li> 4 Extraction</li>
            <li>5 Scrub</li>
            <li>6 Back Scrub</li>
            <li> Windows</li>
            <li>8 Grand Opening</li>
            <li>9 ½ Strip</li>
            <li>10 Other</li>
            <li>11 Corrective Basic</li>
            <li>12 Corrective Front Strip</li>
            <li>13 Corrective Back Strip</li>
            <li>14 Corrective Extraction</li>
            <li>15 Corrective Scrub</li>
            <li>16 Corrective Buff</li>
            <li>17 Corrective Windows</li>
            <li>18 P-Wash</li>
            <li>19 Construction Clean Up</li>
            <li>20 Store Miss</li>
            <li>21 Store Canceled</li>
            <li>22 We Canceled</li>
            <li>23 We Missed </li>
            <li>24 AWOL </li>
            <li>25 Vehicle Problems</li>
            <li>26 Refurbish </li>
            <li>27     Partial Refurbish</li>
            <li>28     Support Area Strip</li>
        </ul>
    </p>
    <%= f.text_field :service_type, class: 'form-control', placeholder: "Enter Service Type" %>
    </div>
    <div class="form-group">
    <%= f.label "Frequency" %>
    <p> Please enter the frequency for each service type input above. For example, '1 - weekly, 2 - annually, 4 - daily' if there are multiple service types. </p>
    <%= f.text_field :frequency, class: 'form-control', placeholder: "Enter Frequency" %>
    </div>
    <div class="form-group">
    <%= f.label "Service Price - Contractor" %>
    <p> Please enter the Contractor service price for each service type.  For example ' 1 - $3400, 2 - $12,000'
    <%= f.text_field :sp_sub, class: 'form-control', placeholder: "Enter Service Price for Contractor" %>
    </div>
    <div class="form-group">
    <%= f.label "Service Price - Corporate" %>
    <p> Please enter the Corporate service price for each service type.  For example ' 1 - $3400, 2 - $12,000'
    <%= f.text_field :sp_corp, class: 'form-control', placeholder: "Enter Service Price for Corporate" %>
    </div>
    <div class="form-group">
    <%= f.label "Square Footage and Floor Type" %>
    <p> Please enter the square footage of the store and the floor type worked upon. For example ' 1400 sq ft - linoleum'
    <%= f.text_field :square_footage, class: 'form-control', placeholder: "Enter Square Footage and Floor Type" %>
    </div>
	
 	<div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
 	<% end %>
	</div>

app/views/stores/show.html.erb
<h2> Store: <%= @store.name %></h2>
<% if policy(Account.new).create? %>
<%= link_to "Edit", edit_store_path(@store), class: 'btn btn-success' %>
<% end %>
<% if policy(Account.new).destroy? %>
 <%= link_to "Delete Store", @store, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this store?' } %>
<% end %> 


<p><h5>Store Code:</h5> <%= @store.code %></p>
<p><h5>Store Phone:</h5> <%= @store.phone_number%></p>
<p><h5>Store Manager:</h5> <%= @store.manager %></p>
<p><h5>Address:</h5> <%= @store.address %></p>
<p><h5>Zip Code:</h5> <%= @store.zipcode %></p>
<p><h5>State:</h5> <%= @store.state %></p>
<p><h5>City:</h5> <%= @store.city %></p>
<p><h5>Region:</h5> <%= @store.region %></p>
<p><h5>District:</h5> <%= @store.district %></p>
<p><h5>Chain:</h5> <%= @store.chain %></p>
<p><h5>Frequency:</h5> <%= @store.frequency %></p>
<p><h5>Service Price - Contractor:</h5> <%= @store.sp_sub %></p>
<p><h5>Service Price - Corporate:</h5> <%= @store.sp_corp %></p>
<p><h5>Square Footage & Floor Type:</h5> <%= @store.square_footage %></p>



  <div class="row">
   <h2>Service Records</h2>
   
   	 <%= render @service_records %>
     <%= will_paginate @service_records %>
     <%= render 'service_records/form', service_record: @service_record, store: @store %>

    </div>
    <hr>
 </div>