config/routes.rb
Rails.application.routes.draw do
 

  resources :meetings
  devise_for :users
  resources :users

 
  resources :accounts do
  	resources :service_comments do
  	end
  end

 

  resources :accounts do
    resources :stores do
    end
  end

  resources :stores do
    resources :service_records do
      end
  end

  resources :subcontractors do
    resources :employees do
    end
  end
  
  resources :employees 
  resources :stores
  resources :service_records
  resources :calendar 

  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	has_many :service_comments, dependent: :destroy
	has_many :stores, dependent: :destroy

=begin the below sql query works for heroku's postgre sql system (production environment) and will give an error
in the current mysql development environment.
=end 

	def self.search(search)
    where("name ILIKE ? OR account_number ILIKE ? OR code ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
    end


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.order(:name).paginate(page: params[:page], per_page: 10)
    authorize @accounts 

  if params[:search]
    @accounts = Account.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 10)
  else
    @accounts = Account.order(:name).paginate(page: params[:page], per_page: 10)
  end

  end

  def show
  	@account = Account.find(params[:id])
    @service_comments = @account.service_comments.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    @service_comment = @account.service_comments.build 
    @stores = @account.stores.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    @store = @account.stores.build
    @all_stores = @account.stores.all.order('created_at DESC')


  end

  def new
    @account = Account.new 
    authorize @account

  end

  def create
    @account = Account.new(params.require(:account).permit(:name, :account_number, :code, :active, :address_1, :address_2, :city,
     :phone_number, :fax_number, :website, :contact_1, :contact_1_title, :contact_1_phone, :contact_1_email, :contact_2, :contact_2_title,
     :contact_2_phone, :contact_2_email, :contact_3, :contact_3_title, :contact_3_phone, :contact_3_email, :accounts_payable_address_1, 
     :accounts_payable_address_2, :accounts_payable_city, :accounts_payable_attn, :accounts_payable_contact_1, :accounts_payable_contact_1_phone,
     :accounts_payable_contact_1_fax, :accounts_payable_contact_1_email, :accounts_payable_contact_2, :accounts_payable_contact_2_phone, 
     :accounts_payable_contact_2_fax, :accounts_payable_contact_2_email, :contracted_services_basic, :contracted_services_strip, :contracted_services_backstrip,
     :contracted_services_extraction, :contracted_services_scrub, :contracted_services_buff, :contracted_services_windows, :contracted_services_grandopening,
     :contracted_services_halfstrip ))
    authorize @account
    if @account.save
      flash[:notice] = "Account was successfully saved."
      redirect_to @account 
    else
      flash[:error] = "There was an error saving your new account. Please try again."
      render :new
    end
  end

  def edit
    @account = Account.find(params[:id])
    authorize @account
  end

  def update
    @account = Account.find(params[:id])
    authorize @account
    if @account.update_attributes(params.require(:account).permit(:name, :account_number, :code, :active, :address_1, :address_2, :city,
     :phone_number, :fax_number, :website, :contact_1, :contact_1_title, :contact_1_phone, :contact_1_email, :contact_2, :contact_2_title,
     :contact_2_phone, :contact_2_email, :contact_3, :contact_3_title, :contact_3_phone, :contact_3_email, :accounts_payable_address_1, 
     :accounts_payable_address_2, :accounts_payable_city, :accounts_payable_attn, :accounts_payable_contact_1, :accounts_payable_contact_1_phone,
     :accounts_payable_contact_1_fax, :accounts_payable_contact_1_email, :accounts_payable_contact_2, :accounts_payable_contact_2_phone, 
     :accounts_payable_contact_2_fax, :accounts_payable_contact_2_email, :contracted_services_basic, :contracted_services_strip, :contracted_services_backstrip,
     :contracted_services_extraction, :contracted_services_scrub, :contracted_services_buff, :contracted_services_windows, :contracted_services_grandopening,
     :contracted_services_halfstrip ))
    flash[:notice] = "Account was updated."
    redirect_to @account
  else
    flash[:error] = "There was an error saving this account. Please try again."
    render :edit
  end
end

def destroy
  @account = Account.find(params[:id])

  if @account.destroy 
    flash[:notice] = "\"#{@account.name}\" was deleted successfully."
    redirect_to accounts_path 
  else
    flash[:error] = "There was an error deleting this account. Please try again."
    render :show
  end
end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<h1>Edit Account</h1>

<div class="row">
	<div class="col-md-4">
		<p> Please fill out form completely and accurately. </p>
		<p> If any issues saving accounts are experienced, please contact your web developer </p>
	</div>

	<div class="col-md-8">
 <%= form_for @account do |f| %>
 	<div class="form-group">
   <%= f.label "Account Name" %>
   <%= f.text_field :name, class: 'form-control', placeholder: "Enter Account Name" %>
    </div>
    <div class="form-group">
    <%= f.label "Account Number" %>
    <%= f.text_field :account_number %>
	</div>
    <div class="form-group">
    <%= f.label "Code" %>
    <%= f.text_field :code %>
    </div>
    <div class="form-group">
    <%= f.label "Active?" %>
    <%= f.check_box :active %>
	</div>
    <div class="form-group">
    <%= f.label "Address 1" %>
    <%= f.text_field :address_1 %>
	</div> 
	<div class="form-group">
    <%= f.label "Address 2" %>
    <%= f.text_field :address_2 %>
    </div>
    <div class="form-group">
   <%= f.label "City" %>
   <%= f.text_field :city %>
    </div>
    <div class="form-group">
   <%= f.label "Phone Number" %>
   <%= f.text_field :phone_number %>
    </div>
    <div class="form-group">
    <%= f.label "Fax Number" %>
   <%= f.text_field :fax_number %>
   </div>
   <div class="form-group">
   <%= f.label "Website" %>
   <%= f.text_field :website %>
   </div>
   <div class="form-group">
   <%= f.label "Primary Contact"%>
   <%= f.text_field :contact_1 %>
   </div>
   <div class="form-group">
   <%= f.label "Title" %>
   <%= f.text_field :contact_1_title %>
	</div>
	<div class="form-group"> 
   <%= f.label "Phone" %>
   <%= f.text_field :contact_1_phone %>
	</div>
	<div class="form-group">
   <%= f.label "Email" %>
   <%= f.text_field :contact_1_email %>
	</div>
	<div class="form-group">
   <%= f.label "Contact" %>
   <%= f.text_field :contact_2 %>
    </div>
    <div class="form-group">
   <%= f.label "Title" %>
   <%= f.text_field :contact_2_title %>
	</div>
	<div class="form-group">
   <%= f.label "Phone" %>
   <%= f.text_field :contact_2_phone %>
	</div>
	<div class="form-group">
   <%= f.label "Email" %>
   <%= f.text_field :contact_2_email %>
	</div>
	<div class="form-group">
   <%= f.label "Contact" %>
   <%= f.text_field :contact_3 %>
   </div>
   <div class="form-group">
   <%= f.label "Title" %>
   <%= f.text_field :contact_3_title %>
	</div>
	<div class="form-group">
   <%= f.label "Phone" %>
   <%= f.text_field :contact_3_phone %>
   </div>
   <div class="form-group">
   <%= f.label "Email" %>
   <%= f.text_field :contact_3_email %>
   </div>
   <div class="form-group">
   <%= f.label "Accounts Payable Address 1" %>
   <%= f.text_field :accounts_payable_address_1 %>
   </div>
   <div class="form-group">
   <%= f.label "Accounts Payable Address 2" %>
   <%= f.text_field :accounts_payable_address_2 %>
   </div>
   <div class="form-group">
   <%= f.label "Accounts Payable City" %>
   <%= f.text_field :accounts_payable_city %>
   </div>
   <div class="form-group">
   <%= f.label "Attn" %>
   <%= f.text_field :accounts_payable_attn %>
	</div>
	<div class="form-group">
   <%= f.label "Accounts Payable Primary Contact" %>
   <%= f.text_field :accounts_payable_contact_1 %>
    </div>
    <div class="form-group">
   <%= f.label "Accounts Payable Primary Contact Phone Number" %>
   <%= f.text_field :accounts_payable_contact_1_phone %>
   </div>
   <div class="form-group">
   <%= f.label "Accounts Payable Primary Contact Fax Number" %>
   <%= f.text_field :accounts_payable_contact_1_fax %>
	</div>
	<div class="form-group">
   <%= f.label "Accounts Payable Primary Contact Email" %>
   <%= f.text_field :accounts_payable_contact_1_email %>
	</div>
	<div class="form-group">
   <%= f.label "Accounts Payable Secondary Contact" %>
   <%= f.text_field :accounts_payable_contact_2 %>
   </div>
   <div class="form-group">
   <%= f.label "Accounts Payable Secondary Contact Phone Number" %>
   <%= f.text_field :accounts_payable_contact_2_phone %>
	</div>
	

   <h4>Contracted Services</h4>
   	<div class="form-group">
    <%= f.label "Basic" %>
    <%= f.check_box :contracted_services_basic %>
    </div>
    <div class="form-group">
    <%= f.label "Strip" %>
    <%= f.check_box :contracted_services_strip %>
	</div>
	<div class="form-group">
    <%= f.label "Backstrip" %>
    <%= f.check_box :contracted_services_backstrip %>
	</div>
	<div class="form-group">
    <%= f.label "Extraction" %>
    <%= f.check_box :contracted_services_extraction %>
	</div>
	<div class="form-group">
    <%= f.label "Scrub" %>
    <%= f.check_box :contracted_services_scrub %>
	</div>
	<div class="form-group">
    <%= f.label "Buff" %>
    <%= f.check_box :contracted_services_buff %>
	</div>
	<div class="form-group">
    <%= f.label "Windows" %>
    <%= f.check_box :contracted_services_windows %>
	</div>
	<div class="form-group">
    <%= f.label "Grand Opening" %>
    <%= f.check_box :contracted_services_grandopening %>
	</div>
	<div class="form-group">
    <%= f.label "Half Strip" %>
    <%= f.check_box :contracted_services_halfstrip %>
 	</div>
 	<div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
 <% end %>

app/views/accounts/index.html.erb
<h1>All Accounts</h1>
<br>
<% if policy(Account.new).create? %>
<p><%= link_to '<button type="button" class="btn btn-default">Create New Account</button>'.html_safe, new_account_path %></p>
<% end %> 
<br>

<%= form_tag(accounts_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search Accounts" %>
    <br>
    <%= submit_tag "Search", :name => nil, class: 'btn btn-success' %>
<% end %>

<% if @accounts.blank? %>
  <h4>There are no accounts containing the term <%= params[:search] %>.</h4>
<% end %>

<br>

<% @accounts.each do |account| %>
  
  <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <p><%= link_to account.name, account_path(account.id) %></p>
       </h4>
     </div>
   </div>
<% end %>
<%= will_paginate @accounts %>

app/views/accounts/new.html.erb
 <h1>Create New Account</h1>

<div class="row">
	<div class="col-md-4">
		<p> Please fill out form completely and accurately. </p>
		<p> If any issues saving accounts are experienced, please contact your web developer </p>
	</div>

	<div class="col-md-8">
 <%= form_for @account do |f| %>
 	<div class="form-group">
   <%= f.label "Account Name" %>
   <%= f.text_field :name, class: 'form-control', placeholder: "Enter Account Name" %>
    </div>
    <div class="form-group">
    <%= f.label "Account Number" %>
    <%= f.text_field :account_number %>
	</div>
    <div class="form-group">
    <%= f.label "Code" %>
    <%= f.text_field :code %>
    </div>
    <div class="form-group">
    <%= f.label "Active?" %>
    <%= f.check_box :active %>
	</div>
    <div class="form-group">
    <%= f.label "Address 1" %>
    <%= f.text_field :address_1 %>
	</div> 
	<div class="form-group">
    <%= f.label "Address 2" %>
    <%= f.text_field :address_2 %>
    </div>
    <div class="form-group">
   <%= f.label "City" %>
   <%= f.text_field :city %>
    </div>
    <div class="form-group">
   <%= f.label "Phone Number" %>
   <%= f.text_field :phone_number %>
    </div>
    <div class="form-group">
    <%= f.label "Fax Number" %>
   <%= f.text_field :fax_number %>
   </div>
   <div class="form-group">
   <%= f.label "Website" %>
   <%= f.text_field :website %>
   </div>
   <div class="form-group">
   <%= f.label "Primary Contact"%>
   <%= f.text_field :contact_1 %>
   </div>
   <div class="form-group">
   <%= f.label "Title" %>
   <%= f.text_field :contact_1_title %>
	</div>
	<div class="form-group"> 
   <%= f.label "Phone" %>
   <%= f.text_field :contact_1_phone %>
	</div>
	<div class="form-group">
   <%= f.label "Email" %>
   <%= f.text_field :contact_1_email %>
	</div>
	<div class="form-group">
   <%= f.label "Contact" %>
   <%= f.text_field :contact_2 %>
    </div>
    <div class="form-group">
   <%= f.label "Title" %>
   <%= f.text_field :contact_2_title %>
	</div>
	<div class="form-group">
   <%= f.label "Phone" %>
   <%= f.text_field :contact_2_phone %>
	</div>
	<div class="form-group">
   <%= f.label "Email" %>
   <%= f.text_field :contact_2_email %>
	</div>
	<div class="form-group">
   <%= f.label "Contact" %>
   <%= f.text_field :contact_3 %>
   </div>
   <div class="form-group">
   <%= f.label "Title" %>
   <%= f.text_field :contact_3_title %>
	</div>
	<div class="form-group">
   <%= f.label "Phone" %>
   <%= f.text_field :contact_3_phone %>
   </div>
   <div class="form-group">
   <%= f.label "Email" %>
   <%= f.text_field :contact_3_email %>
   </div>
   <div class="form-group">
   <%= f.label "Accounts Payable Address 1" %>
   <%= f.text_field :accounts_payable_address_1 %>
   </div>
   <div class="form-group">
   <%= f.label "Accounts Payable Address 2" %>
   <%= f.text_field :accounts_payable_address_2 %>
   </div>
   <div class="form-group">
   <%= f.label "Accounts Payable City" %>
   <%= f.text_field :accounts_payable_city %>
   </div>
   <div class="form-group">
   <%= f.label "Attn" %>
   <%= f.text_field :accounts_payable_attn %>
	</div>
	<div class="form-group">
   <%= f.label "Accounts Payable Primary Contact" %>
   <%= f.text_field :accounts_payable_contact_1 %>
    </div>
    <div class="form-group">
   <%= f.label "Accounts Payable Primary Contact Phone Number" %>
   <%= f.text_field :accounts_payable_contact_1_phone %>
   </div>
   <div class="form-group">
   <%= f.label "Accounts Payable Primary Contact Fax Number" %>
   <%= f.text_field :accounts_payable_contact_1_fax %>
	</div>
	<div class="form-group">
   <%= f.label "Accounts Payable Primary Contact Email" %>
   <%= f.text_field :accounts_payable_contact_1_email %>
	</div>
	<div class="form-group">
   <%= f.label "Accounts Payable Secondary Contact" %>
   <%= f.text_field :accounts_payable_contact_2 %>
   </div>
   <div class="form-group">
   <%= f.label "Accounts Payable Secondary Contact Phone Number" %>
   <%= f.text_field :accounts_payable_contact_2_phone %>
	</div>
	

   <h4>Contracted Services</h4>
   	<div class="form-group">
    <%= f.label "Basic" %>
    <%= f.check_box :contracted_services_basic %>
    </div>
    <div class="form-group">
    <%= f.label "Strip" %>
    <%= f.check_box :contracted_services_strip %>
	</div>
	<div class="form-group">
    <%= f.label "Backstrip" %>
    <%= f.check_box :contracted_services_backstrip %>
	</div>
	<div class="form-group">
    <%= f.label "Extraction" %>
    <%= f.check_box :contracted_services_extraction %>
	</div>
	<div class="form-group">
    <%= f.label "Scrub" %>
    <%= f.check_box :contracted_services_scrub %>
	</div>
	<div class="form-group">
    <%= f.label "Buff" %>
    <%= f.check_box :contracted_services_buff %>
	</div>
	<div class="form-group">
    <%= f.label "Windows" %>
    <%= f.check_box :contracted_services_windows %>
	</div>
	<div class="form-group">
    <%= f.label "Grand Opening" %>
    <%= f.check_box :contracted_services_grandopening %>
	</div>
	<div class="form-group">
    <%= f.label "Half Strip" %>
    <%= f.check_box :contracted_services_halfstrip %>
 	</div>
 	<div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
 <% end %>

app/views/accounts/show.html.erb
<div class=".col-md-8">
<div>
<h2> Account Name: <%= @account.name %></h2>
<% if policy(Account.new).create? %>
<%= link_to "Edit", edit_account_path(@account), class: 'btn btn-success' %>
<% end %>
<% if policy(Account.new).destroy? %>
 <%= link_to "Delete Account", @account, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this account?' } %>
<% end %> 
<p><h5>Account Number:</h5> <%= @account.account_number %></p>
<p><h5>Address 1:</h5> <%= @account.address_1 %></p>
<p><h5>Address 2:</h5> <%= @account.address_2 %></p>
<p><h5>City:</h5> <%= @account.city %></p>
<p><h5>Phone Number:</h5> <%= @account.phone_number %></p>
<p><h5>Fax Number:</h5> <%= @account.fax_number %></p>
<p><h5>Website Address:</h5> <%= @account.website %></p>
<p><h5>Account Primary Contact:</h5> <%= @account.contact_1 %></p>
<p><h5>Phone:</h5> <%= @account.contact_1_phone %></p>
<p><h5>Title:</h5> <%= @account.contact_1_title %></p>
<p><h5>Email Address:</h5> <%= @account.contact_1_email %></p>
<p><h5>Account Contact:</h5> <%= @account.contact_2 %></p> 
<p><h5>Phone:</h5> <%= @account.contact_2_phone %></p>
<p><h5>Title:</h5> <%= @account.contact_2_title %></p>
<p><h5>Email:</h5> <%= @account.contact_2_email %></p>
<p><h5>Account Contact:</h5> <%= @account.contact_3 %></p>
<p><h5>Phone:</h5> <%= @account.contact_3_phone %></p>
<p><h5>Title:</h5> <%= @account.contact_3_title %></p>
<p><h5>Email:</h5> <%= @account.contact_3_email %></p>
<p><h5>Accounts Payable Address 1:</h5><%= @account.accounts_payable_address_1 %></p>
<p><h5>Accounts Payable Address 2:</h5><%= @account.accounts_payable_address_2 %></p>
<p><h5>Accounts Payable City:</h5> <%= @account.accounts_payable_city %></p>
<p><h5>Attn:</h5> <%= @account.accounts_payable_attn %></p>
<p><h5>Accounts Payable Primary Contact:</h5> <%= @account.accounts_payable_contact_1 %></p>
<p><h5>Phone:</h5> <%= @account.accounts_payable_contact_1_phone %></p>
<p><h5>Fax:</h5> <%= @account.accounts_payable_contact_1_fax %></p>
<p><h5>Email:</h5> <%= @account.accounts_payable_contact_1_email %></p>
<p><h5>Contact:</h5> <%= @account.accounts_payable_contact_2 %></p>
<p><h5>Phone:</h5> <%= @account.accounts_payable_contact_2_phone %></p>
<p><h5>Email:</h5> <%= @account.accounts_payable_contact_email %></p>
<h3> Services</h3>
<p><h5>Basic?</h5> <%= @account.contracted_services_basic ? "yes" : "no" %></p>
<p><h5>Strip?</h5> <%= @account.contracted_services_strip ? "yes" : "no" %></p>
<p> <h5>Backstrip?</h5> <%= @account.contracted_services_backstrip ? "yes" : "no" %></p>
<p><h5>Extraction?</h5> <%= @account.contracted_services_extraction ? "yes" : "no" %></p>
<p><h5>Scrub?</h5> <%= @account.contracted_services_scrub ? "yes" : "no" %></p>
<p><h5>Buff?</h5> <%= @account.contracted_services_buff ? "yes" : "no" %></p>
<p><h5>Windows?</h5> <%= @account.contracted_services_windows ? "yes" : "no" %></p>
<p><h5>Grand Opening?</h5> <%= @account.contracted_services_grandopening ? "yes" : "no" %></p>
<p><h5>Half Strip?</h5> <%= @account.contracted_services_halfstrip ? "yes" : "no" %></p>
</div>
<div>
 <hr>
 <div class="row">
   <h2>Stores</h2>

   <% @all_stores.each do |store| %>
  
  <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <p><%= link_to store.name, store_path(store.id) %></p>
       </h4>
     </div>
   </div>
<% end %>

   
    
     <%= render 'stores/form', store: @store, account: @account %>
    
  </div> 
 <hr>

 
  <div class="row">
   <h2>Comments</h2>
  
     <%= render @service_comments %>
     <%= will_paginate @service_comments %>
     <%= render 'service_comments/form', service_comment: @service_comment, account: @account %>
  
  </div>
 <hr>



</div>